// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package packtest1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Test11Client is the client API for Test11 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test11Client interface {
	Heathcheck1(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type test11Client struct {
	cc grpc.ClientConnInterface
}

func NewTest11Client(cc grpc.ClientConnInterface) Test11Client {
	return &test11Client{cc}
}

func (c *test11Client) Heathcheck1(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/module1.packtest1.Test11/Heathcheck1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *test11Client) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/module1.packtest1.Test11/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test11Server is the server API for Test11 service.
// All implementations must embed UnimplementedTest11Server
// for forward compatibility
type Test11Server interface {
	Heathcheck1(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTest11Server()
}

// UnimplementedTest11Server must be embedded to have forward compatible implementations.
type UnimplementedTest11Server struct {
}

func (UnimplementedTest11Server) Heathcheck1(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck1 not implemented")
}
func (UnimplementedTest11Server) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedTest11Server) mustEmbedUnimplementedTest11Server() {}

// UnsafeTest11Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test11Server will
// result in compilation errors.
type UnsafeTest11Server interface {
	mustEmbedUnimplementedTest11Server()
}

func RegisterTest11Server(s grpc.ServiceRegistrar, srv Test11Server) {
	s.RegisterService(&Test11_ServiceDesc, srv)
}

func _Test11_Heathcheck1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test11Server).Heathcheck1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/module1.packtest1.Test11/Heathcheck1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test11Server).Heathcheck1(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test11_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test11Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/module1.packtest1.Test11/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test11Server).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Test11_ServiceDesc is the grpc.ServiceDesc for Test11 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test11_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "module1.packtest1.Test11",
	HandlerType: (*Test11Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck1",
			Handler:    _Test11_Heathcheck1_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Test11_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Test1.proto",
}
